### ISSUE TITLE
Compilation error: 'Can only use .str accessor with string values!'

### ISSUE THREAD

**Issue by amadsalmon** [IheanachorObinna/Whatsapp-Chat-project#3]
_Error message:_

length of df before:0
Traceback (most recent call last):
  File "script.py", line 36, in <module>
    df = df[~df["Name"].str.contains("undefined")]
  File "/usr/local/lib/python3.8/site-packages/pandas/core/generic.py", line 5135, in __getattr__
    return object.__getattribute__(self, name)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/accessor.py", line 187, in __get__
    accessor_obj = self._accessor(obj)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/strings.py", line 2100, in __init__
    self._inferred_dtype = self._validate(data)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/strings.py", line 2157, in _validate
    raise AttributeError("Can only use .str accessor with string values!")
AttributeError: Can only use .str accessor with string values!

I will try to fix the bug and come back to you with a pull request.

**Comment by ObinnaIheanachor** [comment]
Okay, great no problem.

Thank you.
